server:
  port: 9000

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: hello_route
              uri: http://awsgoo-blog-1:8080
              predicates:
                - Path=/hello

            - id: abc2hello_route
              uri: http://awsgoo-blog-1:8080
              predicates:
                - Path=/abc

            - id: def2hello_route
              uri: http://awsgoo-blog-1:8080
              predicates:
                - Path=/def
              filters:
                - RewritePath=/def, /hello

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    # ???(Netty) ???? ?? ?? (??/?? ??)
    reactor.netty: DEBUG

    # Spring WebFlux (????? ?? ??) ?? ??
    org.springframework.web.reactive: DEBUG
