server:
  port: 9000

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: hello_route
              uri: http://awsgoo-blog-1:8080
              predicates:
                - Path=/hello

            - id: user-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /${segment}

            - id: abc2hello_route
              uri: http://awsgoo-blog-1:8080
              predicates:
                - Path=/abc

            - id: def2hello_route
              uri: http://awsgoo-blog-1:8080
              predicates:
                - Path=/def
              filters:
                - RewritePath=/def, /hello

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    # ???(Netty) ???? ?? ?? (??/?? ??)
    reactor.netty: DEBUG

    # Spring WebFlux (????? ?? ??) ?? ??
    org.springframework.web.reactive: DEBUG
